### ISSUE TITLE
Can't use cepstrum.m

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [orchidas/Pitch-Tracking#1]
Hi,

The implementation of 'cepstrum' has a problem it seems. 

```
>> [dat,fs] = readwav('PATAKA.wav');
>> c = cepstrum(dat,fs);
Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Error in cepstrum (line 12)
x = [x, zeros(1,hop*nframes - N + (win-hop))];
```

Hope this helps.

**Comment by orchidas** [comment]
Thanks for reporting. Seems like the function assumes data will be in row or column format by default. Fixed it. Should work now.
