### ISSUE TITLE
don't know where the .csv file come from

### ISSUE THREAD

**Issue by dianaxun** [orchidas/Pitch-Tracking#2]
hello,i run the test_eckf.m under the test directionary,i have already changed the file to be my own file and i ran into an error:crepe =readtable(strcat(soundpath,crepe_filename));unable to open file 'testBad.f0.csv'.i wonder whether you can point out the code that produce the .csv file.thank you, looking forward to hearing from you。

**Comment by orchidas** [comment]
You can comment that line. It just plots the results of the pitch tracker against CREPE. It is not necessary

**Comment by dianaxun** [comment]
> You can comment that line. It just plots the results of the pitch tracker against CREPE. It is not necessary

ok,thank you.
